/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticoviaje.Design;

/**
 *
 * @author hilla
 */
public class BusDesign extends javax.swing.JFrame {

    /**
     * Creates new form BusDesign
     */
    public BusDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton4 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton10 = new javax.swing.JButton();
        Boton18 = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton4MouseClicked(evt);
            }
        });
        jPanel1.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        Boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3MouseClicked(evt);
            }
        });
        jPanel1.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        Boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
        });
        jPanel1.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        Boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton1.setActionCommand("");
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
        });
        jPanel1.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        Boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
        });
        jPanel1.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        Boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton6MouseClicked(evt);
            }
        });
        jPanel1.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        Boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton7MouseClicked(evt);
            }
        });
        jPanel1.add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        Boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton8MouseClicked(evt);
            }
        });
        jPanel1.add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        Boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton9MouseClicked(evt);
            }
        });
        jPanel1.add(Boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        Boton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton10MouseClicked(evt);
            }
        });
        jPanel1.add(Boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        Boton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/asientoDisponible.png"))); // NOI18N
        Boton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton18MouseClicked(evt);
            }
        });
        jPanel1.add(Boton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticoviaje/Imagen/MicrosoftTeams-image (2).png"))); // NOI18N
        jPanel1.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton10MouseClicked

    private void Boton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton9MouseClicked

    private void Boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton8MouseClicked

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton7MouseClicked

    private void Boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton6MouseClicked

    private void Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton4MouseClicked

    private void Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton3MouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton18MouseClicked

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusDesign().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton10;
    private javax.swing.JButton Boton18;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
